// De enige geldige actienamen in het auditlog. Bron: ADR-0003 (eventset), gebaseerd op
// ui-spec/state/audit-event-model.md.
// TODO(B-F): ADR-0003 heeft status 'Voorgesteld'; na vaststelling deze regel weghalen.

export const AUDIT_ACTIES = [
  "TASK_CREATED",
  "SELECTION_REQUESTED",
  "SELECTION_RETRY_REQUESTED",
  "SELECTION_COMPLETED",
  "OBJECT_INCLUDED",
  "OBJECT_EXCLUDED",
  "REVIEW_SUBMITTED",
  "APPROVAL_GRANTED",
  "APPROVAL_REJECTED",
  "DESTRUCTION_APPROVED_BY_ARCHIVIST",
  "DESTRUCTION_ORDERED_BY_RM",
  "EXECUTION_STARTED",
  "BATCH_STARTED",
  "BATCH_COMPLETED",
  "OBJECT_PROCESSED",
  "OBJECT_FAILED",
  "EXECUTION_FAILED",
  "EXECUTION_RETRY_REQUESTED",
  "EXECUTION_COMPLETED",
  "CERTIFICATE_GENERATED",
  "ARCHIVING_REQUESTED",
  "ARCHIVING_FAILED",
  "TASK_COMPLETED",
  "TASK_DELETED",
] as const;

export type AuditActie = (typeof AUDIT_ACTIES)[number];

export const CONFIGURATIE_ACTIES = [
  "MASTER_DATA_IMPORTED",
  "TASK_DEFINITION_CREATED",
  "USER_LINKED",
  "CONNECTOR_CREATED",
  "CONNECTOR_UPDATED",
  "CONNECTOR_DEACTIVATED",
  "CONNECTOR_ACTIVATED",
  "CONNECTOR_DELETED",
  "TASK_DEFINITION_DELETED",
] as const;

export type ConfiguratieActie = (typeof CONFIGURATIE_ACTIES)[number];
